# Generated by Django 5.1.6 on 2025-02-11 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('total_emissions', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity', models.FloatField()),
                ('diesel', models.FloatField()),
                ('petrol', models.FloatField()),
                ('lpg', models.FloatField()),
                ('water_supply', models.FloatField()),
                ('wastewater_treatment', models.FloatField()),
                ('organic_waste', models.FloatField()),
                ('plastic_waste', models.FloatField()),
                ('sewage_treatment', models.FloatField()),
                ('paper', models.FloatField()),
                ('refrigerant_gwp', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EnergyConsumption',
            fields=[
                ('emi_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='emissions.emissiondata')),
                ('electricity_kwh', models.FloatField()),
                ('solar_generation_kwh', models.FloatField()),
                ('generator_fuel_liters', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FuelConsumption',
            fields=[
                ('emi_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='emissions.emissiondata')),
                ('diesel_liters', models.FloatField()),
                ('petrol_liters', models.FloatField()),
                ('lpg_kg', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('emi_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='emissions.emissiondata')),
                ('distance_by_bus_km', models.FloatField()),
                ('distance_by_personal_km', models.FloatField()),
                ('distance_by_public_km', models.FloatField()),
                ('distance_by_ev_km', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WasteManagement',
            fields=[
                ('emi_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='emissions.emissiondata')),
                ('organic_waste_kg', models.FloatField()),
                ('plastic_waste_kg', models.FloatField()),
                ('sewage_liters', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WaterUsage',
            fields=[
                ('emi_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='emissions.emissiondata')),
                ('water_consumed_kl', models.FloatField()),
                ('wastewater_treated_kl', models.FloatField()),
            ],
        ),
    ]
