# Generated by Django 5.1.6 on 2025-02-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissiondata',
            name='total_emissions',
            field=models.FloatField(default=0.0),
        ),
    ]
