# Generated by Django 5.1.6 on 2025-02-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0003_alter_emissiondata_total_emissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissiondata',
            name='diesel_emissions',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='emissiondata',
            name='electricity_emissions',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='emissiondata',
            name='lpg_emissions',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='emissiondata',
            name='petrol_emissions',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='emissiondata',
            name='plastic_waste_emissions',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='emissiondata',
            name='public_transport_emissions',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='emissiondata',
            name='water_supply_emissions',
            field=models.FloatField(default=0.0),
        ),
    ]
