# Generated by Django 5.1.6 on 2025-02-24 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0004_emissiondata_diesel_emissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperUsage',
            fields=[
                ('emi_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='emissions.emissiondata')),
                ('paper_kg', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='wastemanagement',
            name='ewaste_kg',
            field=models.FloatField(default=0.0),
        ),
    ]
