# Generated by Django 5.1.6 on 2025-02-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0005_paperusage_wastemanagement_ewaste_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastemanagement',
            name='ewaste_kg',
            field=models.FloatField(),
        ),
    ]
