# Generated by Django 5.1.6 on 2025-02-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0006_alter_wastemanagement_ewaste_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissiondata',
            name='paper_emissions',
            field=models.FloatField(default=0.0),
        ),
    ]
