# Generated by Django 5.1.6 on 2025-02-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0007_emissiondata_paper_emissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissiondata',
            name='ewaste_emissions',
            field=models.FloatField(default=0.0),
        ),
    ]
