# Generated by Django 5.1.6 on 2025-02-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0008_emissiondata_ewaste_emissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionfactor',
            name='ewaste',
            field=models.FloatField(default=0.0),
        ),
    ]
