# Generated by Django 5.1.6 on 2025-03-02 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0009_emissionfactor_ewaste'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyEnergyConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('electricity_kwh', models.FloatField()),
                ('solar_generation_kwh', models.FloatField()),
                ('generator_fuel_liters', models.FloatField()),
                ('emi_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.emissiondata')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyFuelConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('diesel_liters', models.FloatField()),
                ('petrol_liters', models.FloatField()),
                ('lpg_kg', models.FloatField()),
                ('emi_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.emissiondata')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyPaperUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('paper_kg', models.FloatField()),
                ('emi_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.emissiondata')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyTransportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('distance_by_bus_km', models.FloatField()),
                ('distance_by_personal_km', models.FloatField()),
                ('distance_by_public_km', models.FloatField()),
                ('distance_by_ev_km', models.FloatField()),
                ('emi_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.emissiondata')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyWasteManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('organic_waste_kg', models.FloatField()),
                ('plastic_waste_kg', models.FloatField()),
                ('sewage_liters', models.FloatField()),
                ('ewaste_kg', models.FloatField()),
                ('emi_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.emissiondata')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyWaterUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('water_consumed_kl', models.FloatField()),
                ('wastewater_treated_kl', models.FloatField()),
                ('emi_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.emissiondata')),
            ],
        ),
    ]
