# Generated by Django 5.1.6 on 2025-03-02 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0009_emissionfactor_ewaste'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyEmissionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('is_complete', models.BooleanField(default=False)),
                ('electricity_kwh', models.FloatField(default=0)),
                ('solar_generation_kwh', models.FloatField(default=0)),
                ('generator_fuel_liters', models.FloatField(default=0)),
                ('diesel_liters', models.FloatField(default=0)),
                ('petrol_liters', models.FloatField(default=0)),
                ('lpg_kg', models.FloatField(default=0)),
                ('distance_by_bus_km', models.FloatField(default=0)),
                ('distance_by_personal_km', models.FloatField(default=0)),
                ('distance_by_public_km', models.FloatField(default=0)),
                ('distance_by_ev_km', models.FloatField(default=0)),
                ('water_consumed_kl', models.FloatField(default=0)),
                ('wastewater_treated_kl', models.FloatField(default=0)),
                ('organic_waste_kg', models.FloatField(default=0)),
                ('plastic_waste_kg', models.FloatField(default=0)),
                ('sewage_liters', models.FloatField(default=0)),
                ('ewaste_kg', models.FloatField(default=0)),
                ('paper_kg', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'year', 'month')},
            },
        ),
    ]
