# Generated by Django 5.1.6 on 2025-03-02 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0010_monthlyenergyconsumption_monthlyfuelconsumption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyenergyconsumption',
            name='emi_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emissions.emissiondata'),
        ),
        migrations.AlterField(
            model_name='monthlyfuelconsumption',
            name='emi_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emissions.emissiondata'),
        ),
        migrations.AlterField(
            model_name='monthlypaperusage',
            name='emi_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emissions.emissiondata'),
        ),
        migrations.AlterField(
            model_name='monthlytransportation',
            name='emi_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emissions.emissiondata'),
        ),
        migrations.AlterField(
            model_name='monthlywastemanagement',
            name='emi_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emissions.emissiondata'),
        ),
        migrations.AlterField(
            model_name='monthlywaterusage',
            name='emi_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emissions.emissiondata'),
        ),
    ]
