# Generated by Django 5.1.6 on 2025-03-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0010_monthlyemissiondata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyemissiondata',
            name='diesel_liters',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyemissiondata',
            name='distance_by_bus_km',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyemissiondata',
            name='distance_by_ev_km',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyemissiondata',
            name='distance_by_personal_km',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyemissiondata',
            name='distance_by_public_km',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyemissiondata',
            name='electricity_kwh',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyemissiondata',
            name='ewaste_kg',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyemissiondata',
            name='generator_fuel_liters',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyemissiondata',
            name='lpg_kg',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyemissiondata',
            name='organic_waste_kg',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyemissiondata',
            name='paper_kg',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyemissiondata',
            name='petrol_liters',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyemissiondata',
            name='plastic_waste_kg',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyemissiondata',
            name='sewage_liters',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyemissiondata',
            name='solar_generation_kwh',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyemissiondata',
            name='wastewater_treated_kl',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyemissiondata',
            name='water_consumed_kl',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
