# Generated by Django 5.1.6 on 2025-03-09 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0012_monthlyemissiondata_one_year_per_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodConsumption',
            fields=[
                ('emi_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='emissions.emissiondata')),
                ('red_meat_kg', models.FloatField()),
                ('poultry_kg', models.FloatField()),
                ('vegetables_kg', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Refrigerants',
            fields=[
                ('emi_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='emissions.emissiondata')),
                ('r134a_kg', models.FloatField()),
                ('r410a_kg', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='emissiondata',
            name='poultry_emissions',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='emissiondata',
            name='r134a_emissions',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='emissiondata',
            name='r410a_emissions',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='emissiondata',
            name='red_meat_emissions',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='emissiondata',
            name='vegetables_emissions',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='emissionfactor',
            name='poultry',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='emissionfactor',
            name='r134a',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='emissionfactor',
            name='r410a',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='emissionfactor',
            name='red_meat',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='emissionfactor',
            name='vegetables',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='monthlyemissiondata',
            name='poultry_kg',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='monthlyemissiondata',
            name='r134a_kg',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='monthlyemissiondata',
            name='r410a_kg',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='monthlyemissiondata',
            name='red_meat_kg',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='monthlyemissiondata',
            name='vegetables_kg',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
