# Generated by Django 5.1.6 on 2025-03-02 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0012_alter_monthlyenergyconsumption_emi_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlytransportation',
            name='emi_data',
        ),
        migrations.RemoveField(
            model_name='monthlywastemanagement',
            name='emi_data',
        ),
        migrations.RemoveField(
            model_name='monthlywaterusage',
            name='emi_data',
        ),
        migrations.AlterField(
            model_name='monthlyenergyconsumption',
            name='emi_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.emissiondata'),
        ),
        migrations.AlterField(
            model_name='monthlyfuelconsumption',
            name='emi_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.emissiondata'),
        ),
        migrations.DeleteModel(
            name='MonthlyPaperUsage',
        ),
        migrations.DeleteModel(
            name='MonthlyTransportation',
        ),
        migrations.DeleteModel(
            name='MonthlyWasteManagement',
        ),
        migrations.DeleteModel(
            name='MonthlyWaterUsage',
        ),
    ]
