# Generated by Django 5.1.6 on 2025-03-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0013_foodconsumption_refrigerants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionfactor',
            name='public_transport',
            field=models.FloatField(default=1.0),
        ),
    ]
