# Generated by Django 5.1.5 on 2025-01-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('total_campus_area', models.FloatField()),
                ('total_builtup_area', models.FloatField()),
                ('lawn_garden_area', models.FloatField()),
                ('undeveloped_land_area', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('factor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EnergyConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('electricity_kwh', models.FloatField()),
                ('solar_generation_kwh', models.FloatField()),
                ('generator_fuel_liters', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('total_students_staff', models.IntegerField()),
                ('distance_by_bus_km', models.FloatField()),
                ('distance_by_personal_vehicles_km', models.FloatField()),
                ('distance_by_public_transport_km', models.FloatField()),
                ('distance_by_ev_km', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WasteManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('waste_generated_tonnes', models.FloatField()),
                ('waste_treated_tonnes', models.FloatField()),
                ('waste_to_landfill_tonnes', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WaterUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('water_consumed_kl', models.FloatField()),
                ('rainwater_harvesting_capacity', models.FloatField()),
                ('wastewater_treated_kl', models.FloatField()),
            ],
        ),
    ]
