# Generated by Django 5.1.5 on 2025-01-26 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_collegedetails_user_energyconsumption_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energyconsumption',
            name='user',
        ),
        migrations.RemoveField(
            model_name='energyconsumption',
            name='year',
        ),
        migrations.RemoveField(
            model_name='transportation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transportation',
            name='year',
        ),
        migrations.RemoveField(
            model_name='wastemanagement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wastemanagement',
            name='year',
        ),
        migrations.RemoveField(
            model_name='waterusage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='waterusage',
            name='year',
        ),
        migrations.CreateModel(
            name='YearlyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='energyconsumption',
            name='yearly_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.yearlydata'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='yearly_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.yearlydata'),
        ),
        migrations.AddField(
            model_name='wastemanagement',
            name='yearly_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.yearlydata'),
        ),
        migrations.AddField(
            model_name='waterusage',
            name='yearly_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.yearlydata'),
        ),
    ]
